# Generated by Django 5.1.8 on 2025-04-20 09:53

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_of_trades', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField()),
                ('volume_weighted_average', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 week')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_quotes', to='market.company')),
            ],
        ),
    ]
