# Generated by Django 5.1.8 on 2025-04-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_stockquotes_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquotes',
            name='volume_weighted_average',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
