# Generated by Django 5.1.8 on 2025-04-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_stockquotes_volume_weighted_average'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stockquotes',
            managers=[
            ],
        ),
    ]
