# Generated by Django 5.1.8 on 2025-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_stockquotes_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquotes',
            name='volume_weighted_average',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
