# Generated by Django 5.1.8 on 2025-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_stockquotes_volume_weighted_average'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquotes',
            unique_together={('company', 'time')},
        ),
    ]
